Clean Up Datahub Formatting
mozilla/mozilla-datahub-ingestion pull request #92
Opened 2024-03-29 18:25 UTC by jmsilverman

There are some formatting weirdnesses in Datahub when going from the metric-hub source code to yaml as parsed by Datahub. This PR:
- Boldifies some field headings in the Metric Description to make them easier to read
- Removes underscores that were supposed to italicize the main Metric Description but that often broke
- Replaces linebreaks in Metric Descriptions with spaces to make them easier to read
- Adds necessary line breaks in code blocks so all text is displayed
- Adds `sql` tag to SQL Definition code blocks to utilize code highlighting

This PR also makes a few small edits to comments & documentation.

2024-03-29 18:26 UTC, jmsilverman commented on sync/datahub/metrichub_glossary.py
> +        "owners": {}, # [], ## list led to "validation error for BusinessGlossaryConfig"
I had to make this change to be able to run a local version of Datahub on a newly-created yaml file...

2024-04-01 18:04 UTC, jmsilverman commented on sync/datahub/metrichub_glossary.py
> +        metric_content += f"**Data Source:** {metric.data_source} {metric.bigquery_tables}\n\n"
As the FIXME comment states, it would be nice to have one or both of these fields link out to datahub or BQ, respectively, I just couldn't figure out how to do that.

2024-04-01 18:09 UTC, jmsilverman commented
Below are a few screenshots of the local version of datahub running on my machine with this PR's changes and links to the corresponding pages in the production version of datahub for comparison.

[Days of Use (production)](https://mozilla.acryl.io/glossaryTerm/urn:li:glossaryTerm:Metric%20Hub.firefox_desktop.days_of_use/Documentation?is_lineage_mode=false)
<img width="1512" alt="Screenshot 2024-04-01 at 11 05 13 AM" src="https://github.com/mozilla/mozilla-datahub-ingestion/assets/6233701/72a702ef-f244-4a7f-8fe2-40783ea86bb7">

[Desktop DAU KPI deprecated (production)](https://mozilla.acryl.io/glossaryTerm/urn:li:glossaryTerm:Metric%20Hub.firefox_desktop.desktop_dau_kpi/Documentation?is_lineage_mode=falsel)
<img width="1512" alt="Screenshot 2024-04-01 at 11 05 24 AM" src="https://github.com/mozilla/mozilla-datahub-ingestion/assets/6233701/bade14ea-4c62-495b-8321-de6739915923">

[Desktop DAU KPI (production w/out Metric Level](https://mozilla.acryl.io/glossaryTerm/urn:li:glossaryTerm:Metric%20Hub.firefox_desktop.desktop_dau_kpi_v2/Documentation?is_lineage_mode=false)
<img width="1512" alt="Screenshot 2024-04-01 at 11 00 47 AM" src="https://github.com/mozilla/mozilla-datahub-ingestion/assets/6233701/559a6f04-9132-4bde-b198-37c7c1f91ccb">

2024-04-02 15:14 UTC, ANich requested changes

2024-04-02 15:14 UTC, ANich commented on README.md
> +2. Activate the virtual environment: `$ source venv/bin/activate`
👍

2024-04-02 15:14 UTC, ANich commented on sync/datahub/metrichub_glossary.py
> +        metric_content += f"{metric.description.strip().replace(linesep, ' ')}\n\n"
nit: I haven't looked at examples here but maybe `. ` as a sentence separator? Feel free to ignore 
```suggestion
        metric_content += f"{metric.description.strip().replace(linesep, '. ')}\n\n"
```

2024-04-02 15:59 UTC, jmsilverman commented on sync/datahub/metrichub_glossary.py
> +        metric_content += f"**Data Source:** {metric.data_source} {metric.bigquery_tables}\n\n"
Awesome! Is there a ticket or other docs about the plan to use that section for this?
Also, would you then recommend that I just remove these 4 lines completely or instead just remove the comment but still display `data_source` and/or `bigquery_tables` as plain text?

2024-04-02 17:39 UTC, jmsilverman commented on sync/datahub/metrichub_glossary.py
> +        metric_content += f"{metric.description.strip().replace(linesep, ' ')}\n\n"
Yeah, in the metrichub definitions I've looked it, it looks like people are adding line breaks when the lines are too long and/or when they're ends of sentences and in the latter case they include a period, so I don't think we need to include `.` here.

2024-04-02 19:05 UTC, ANich commented on sync/datahub/metrichub_glossary.py
> +        metric_content += f"**Data Source:** {metric.data_source} {metric.bigquery_tables}\n\n"
Here are the details: https://mozilla-hub.atlassian.net/browse/DENG-3296 I think you can remove this altogether, no need to duplicate logic here

2024-04-02 21:11 UTC, merged